-- CREATE DATABASE EnglishDB;
-- \c englishdb;
-- \i '/Users/lucasgrospellier/Documents/english-app/db_files/db_data.sql'
-- Insert sample data
INSERT INTO users (login, password, firstname, lastname) 
VALUES 
('alice@example.com','$2b$10$dr5qfCazDFtHGwqY6RRLvuDWDnzsrkRyUJSPuKzC/7v7c1FPjxkSm','alice', 'dupont'), -- password : mdp
('lucas.grospellier@orange.fr','$2b$10$7AfJr7IsMcJAdCLVSVYTce244AnFFm50lS5/OEYSkJ0R4WkF6GPlW','lucas', 'grospellier');-- password : lucasmdp

INSERT INTO lesson (lesson_type, lesson_title, lesson_content, lesson_importance, lesson_level) 
VALUES 
('grammer', 'Futur continuous', 
'{"description": "This lesson is about futur continuous", "examples": ["When you come out of school tomorrow, I''ll be boarding a plane.",
"Try to call before 8 o''clock. After that, we''ll be watching the match.",
"You can visit us during the first week of July. I won''t be working then."]}', 2, 'B2'),

('Grammar', 'Nouns', '{"description": "Nouns are words that indicate a person, place, or thing. In a sentence, nouns can function as the subject or the object of a verb or preposition. Nouns can also follow linking verbs to rename or re-identify the subject of a sentence or clause; these are known as predicate nouns.", "examples": ["cat", "book", "table", "girl", "plane", "The dog chased its tail. (tail is the direct object)", "Mary reads a book every week. (book is the direct object)", "Please pass Jeremy the salt. (Jeremy is the indirect object)", "Your backpack is under the table. (table is the object of the preposition)", "Love is a virtue. (virtue is a predicate noun)"], "short_summary": {"description": "Nouns are words that indicate a person, place, or thing.", "example": "cat"}}', 5, 'A1'),
('Grammar', 'Common and Proper Nouns', '{"description": "Common nouns are general names for people, places, things, or ideas (e.g., city, river, person). Proper nouns are specific names for people, places, organizations, or sometimes things. Proper nouns are always capitalized (e.g., Paris, Nile, John).", "examples": ["Common: city, river, person", "Proper: Paris, Nile, John"], "short_summary": {"description": "Common nouns are general names, proper nouns are specific and capitalized.", "example": "city vs Paris"}}', 4, 'A1'),
('Grammar', 'Concrete and Abstract Nouns', '{"description": "Concrete nouns are nouns that refer to people or things that exist physically and can be perceived by the senses (e.g., house, music). Abstract nouns are nouns that refer to ideas, feelings, qualities, or concepts that cannot be perceived by the senses (e.g., love, courage).", "examples": ["Concrete: house, music", "Abstract: love, courage"], "short_summary": {"description": "Concrete nouns are physical, abstract nouns are ideas or feelings.", "example": "house vs love"}}', 3, 'A1'),
('Grammar', 'Countable Nouns', '{"description": "Countable nouns are nouns that can be counted. They have both singular and plural forms (e.g., apple, apples; book, books). They can be used with numbers and quantifiers like ''many'' or ''few''.", "examples": ["one apple, two apples", "a book, many books"], "short_summary": {"description": "Countable nouns can be counted and have plural forms.", "example": "one apple, two apples"}}', 4, 'A1'),
('Grammar', 'Uncountable Nouns', '{"description": "Uncountable nouns are nouns that cannot be counted. They do not typically have a plural form and are used with singular verbs (e.g., water, information, advice). They can be used with quantifiers like ''much'' or ''little''.", "examples": ["water", "information", "advice"], "short_summary": {"description": "Uncountable nouns cannot be counted and don''t usually have plurals.", "example": "water"}}', 4, 'A1'),
('Grammar', 'Articles', '{"description": "Articles are words (a, an, the) used before nouns to specify whether the noun is general or specific. ''A'' and ''an'' are indefinite articles, used with singular countable nouns. ''The'' is the definite article, used with specific nouns (singular or plural, countable or uncountable).", "examples": ["a cat", "an apple", "the sun", "the cats"], "short_summary": {"description": "Articles (a, an, the) specify nouns.", "example": "a cat, the sun"}}', 5, 'A1'),
('Grammar', 'Determiners', '{"description": "Determiners are words that come before a noun to clarify what the noun refers to. They include articles (a, an, the), possessives (my, your, his, her, its, our, their), demonstratives (this, that, these, those), and quantifiers (some, any, many, much, few, little).", "examples": ["my book", "this car", "some water"], "short_summary": {"description": "Determiners specify nouns (articles, possessives, etc.).", "example": "my book"}}', 3, 'A1'),
('Grammar', 'Personal pronouns', '{"description": "Personal pronouns are pronouns that refer to a specific person or thing. They change form depending on their number (singular or plural), person (first, second, or third), gender (for third person singular), and case (subject, object, or possessive).", "examples": ["I", "you", "he", "she", "it", "we", "they"], "short_summary": {"description": "Personal pronouns replace nouns for people or things.", "example": "I, you, he"}}', 5, 'A1'),
('Grammar', 'Personal Pronouns - Number', '{"description": "Personal pronouns have different forms depending on whether they refer to one person/thing (singular) or more than one (plural). Singular pronouns include I, you, he, she, it. Plural pronouns include we, you, they.", "examples": ["Singular: I, he, she, it", "Plural: we, they"], "short_summary": {"description": "Pronouns are singular (I) or plural (we).", "example": "I vs we"}}', 4, 'A1'),
('Grammar', 'Personal Pronouns - Person (First person, Second person, Third person)', '{"description": "Personal pronouns are categorized by person: First person refers to the speaker(s) (I, we). Second person refers to the listener(s) (you). Third person refers to someone or something else (he, she, it, they).", "examples": ["First person: I, we", "Second person: you", "Third person: he, she, it, they"], "short_summary": {"description": "Pronouns are first (I), second (you), or third person (he).", "example": "I, you, he"}}', 4, 'A1'),
('Grammar', 'Personal Pronouns - Gender', '{"description": "In the third person singular, personal pronouns can indicate gender: ''he'' is used for males, ''she'' is used for females, and ''it'' is used for things or animals (when the gender is unknown or irrelevant).", "examples": ["He for males", "She for females", "It for things/animals"], "short_summary": {"description": "Some pronouns show gender (he, she, it).", "example": "he, she, it"}}', 3, 'A1'),
('Grammar', 'Verbs', '{"description": "Verbs are words that describe an action, state, or occurrence. They are essential parts of a sentence, typically forming the predicate. Verbs change form based on tense (past, present, future), person, and number.", "examples": ["run", "is", "happen", "eat", "sleep"], "short_summary": {"description": "Verbs show action or a state of being.", "example": "run"}}', 5, 'A1'),
('Grammar', 'Regular and Irregular Verbs (Basic)', '{"description": "Regular verbs form their past tense and past participle by adding ''-ed'' to the base form (e.g., walk - walked - walked). Irregular verbs have different, often unpredictable, forms for the past tense and past participle (e.g., go - went - gone; eat - ate - eaten). This lesson covers basic irregular verbs.", "examples": ["Regular: walk - walked", "Irregular: go - went"], "short_summary": {"description": "Verbs are regular (-ed) or irregular (go-went).", "example": "walked vs went"}}', 4, 'A1'),
('Grammar', 'Present Tense', '{"description": "The present tense is used to describe actions happening now, habitual actions or routines, facts, and general truths. It is a fundamental tense in English.", "examples": ["I eat breakfast every day.", "The sun rises in the east."], "short_summary": {"description": "Present tense is for now or routines.", "example": "I eat"}}', 5, 'A1'),
('Grammar', 'Present Simple Tense', '{"description": "The present simple tense is formed using the base form of the verb (add -s for third person singular). It is used for habits, routines, facts, general truths, scheduled events, and states.", "examples": ["I play football.", "She reads a book every day.", "The train leaves at 7 AM."], "short_summary": {"description": "Present simple for facts and habits.", "example": "I play"}}', 5, 'A1'),
('Grammar', 'Adjectives', '{"description": "Adjectives are words that describe or modify nouns and pronouns, providing more information about their qualities or characteristics. They answer questions like ''what kind?'', ''which one?'', or ''how many?''.", "examples": ["big house", "happy child", "blue sky", "interesting book"], "short_summary": {"description": "Adjectives describe nouns.", "example": "big house"}}', 5, 'A1'),
('Grammar', 'Attributive Adjectives', '{"description": "Attributive adjectives are adjectives that typically appear before the noun they modify. They are a common way to add descriptive detail to nouns.", "examples": ["a red car", "a tall building", "an interesting story"], "short_summary": {"description": "Attributive adjectives are before nouns (red car).", "example": "red car"}}', 3, 'A1'),
('Grammar', 'Predicative Adjectives', '{"description": "Predicative adjectives are adjectives that follow a linking verb (such as be, seem, become) and describe the subject of the sentence or clause. They form part of the predicate.", "examples": ["The car is red.", "He is happy.", "She seems tired."], "short_summary": {"description": "Predicative adjectives are after linking verbs (is red).", "example": "is red"}}', 3, 'A1'),
('Grammar', 'Degrees of Comparison (Basic - e.g., bigger, biggest)', '{"description": "Adjectives and adverbs can be used to compare things. The basic degrees of comparison are the positive (e.g., big), the comparative (e.g., bigger, used to compare two things), and the superlative (e.g., biggest, used to compare three or more things). This lesson introduces the basic forms.", "examples": ["big, bigger, biggest", "happy, happier, happiest"], "short_summary": {"description": "Comparing things with adjectives (bigger, biggest).", "example": "bigger"}}', 4, 'A1'),
('Grammar', 'Adverbs (Basic - e.g., Adverbs of Time, Place)', '{"description": "Adverbs are words that modify verbs, adjectives, other adverbs, or entire sentences, providing more information about manner, place, time, frequency, or degree. This lesson focuses on basic adverbs of time and place.", "examples": ["He runs quickly.", "She is here.", "They arrived yesterday."], "short_summary": {"description": "Adverbs describe verbs/adjectives (runs quickly).", "example": "quickly"}}', 4, 'A1'),
('Grammar', 'Prepositions (Basic - e.g., Categories of Prepositions)', '{"description": "Prepositions are words that show the relationship between a noun or pronoun and other words in a sentence, often indicating location, direction, time, or manner. This lesson covers basic prepositions and simple categories.", "examples": ["in the box", "on the table", "at home", "to the store"], "short_summary": {"description": "Prepositions show relationships (in the box, on the table).", "example": "in the box"}}', 4, 'A1'),
('Grammar', 'Conjunctions (Basic - e.g., Coordinating Conjunctions)', '{"description": "Conjunctions are words used to connect words, phrases, clauses, or sentences. Coordinating conjunctions (such as and, but, or) connect elements of equal grammatical rank.", "examples": ["and", "but", "or", "He likes tea and coffee.", "She is tired, but she needs to finish."], "short_summary": {"description": "Conjunctions connect words or sentences (and, but, or).", "example": "and"}}', 3, 'A1'),
('Grammar', 'Sentences (Basic - e.g., Declarative Sentences)', '{"description": "A sentence is a group of words that expresses a complete thought. Basic sentences typically contain a subject and a predicate. Declarative sentences are the most common type, used to make statements.", "examples": ["The sun is hot.", "Birds can fly.", "I am learning English."], "short_summary": {"description": "Basic sentences make statements.", "example": "The sun is hot."}}', 5, 'A1'),



('Vocabulary', 'Common English Idioms', 
'{"description": "This lesson covers common English idioms and their meanings.", 
   "examples": [
     {"idiom": "Break the ice", "meaning": "To start a conversation in a social setting."},
     {"idiom": "Piece of cake", "meaning": "Something that is very easy to do."},
     {"idiom": "Under the weather", "meaning": "Feeling unwell or sick."}
   ]}', 
 5, 'B1');

INSERT INTO question (question_type, question_content) 
VALUES 
('MCQ', '{"question": "What will you be doing tomorrow at 3 PM?", "options": ["I will be reading a book.", "I will read a book.", "I am reading a book.", "I have read a book."], "correct_answer": "I will be reading a book."}'),
('MCQ', '{"question": "What is the correct sentence for future continuous?", "options": ["He will be work tomorrow.", "He will be working tomorrow.", "He will work tomorrow.", "He will working tomorrow."], "correct_answer": "He will be working tomorrow."}');

INSERT INTO lesson_result (user_id, lesson_id, lesson_completion, lesson_right_answer) 
VALUES 
(1, 1, 90, 80),
(1, 2, 75, 60);
